# Generated by Django 3.0.7 on 2020-08-01 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemType', models.TextField()),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('url', models.TextField()),
                ('rating', models.FloatField()),
                ('numSold', models.IntegerField()),
                ('img', models.TextField()),
                ('shipping', models.FloatField()),
                ('score', models.FloatField()),
            ],
        ),
    ]
